[tool.poetry]
name = "ndpi-tiler"
version = "0.1.0"
description = ""
authors = ["Erik O Gabrielsson <erik.o.gabrielsson@sectra.com>"]

[tool.poetry.dependencies]
python = "^3.7"
tifffile = "^2021.6.14"
wsi_PyTurboJPEG = {path = "c:/work/wsi-PyTurboJPEG/" }

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
