[tool.poetry]
name = "ndpi-tiler"
version = "0.1.0"
description = ""
authors = ["Erik O Gabrielsson <erik.o.gabrielsson@sectra.com>"]

[tool.poetry.dependencies]
python = "^3.7"
tifffile = "^2021.6.14"
PyTurboJPEG = "^1.5.2"
wsidicom = {path = "../wsidicom", develop = true}
pydicom = "^2.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-watch = "^4.2.0"
Pillow = "^8.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
