[tool.poetry]
name = "opentile"
version = "0.1.0"
description = ""
authors = ["Erik O Gabrielsson <erik.o.gabrielsson@sectra.com>"]

[tool.poetry.dependencies]
python = "^3.7"
tifffile = "^2021.6.14"
PyTurboJPEG = { git = "https://github.com/lilohuang/PyTurboJPEG.git" }
Pillow = "^8.3.2"
imagecodecs = "^2021.8.26"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-watch = "^4.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
