name: opentile pytest

on: [push, pull_request]

jobs:
  # RUN PYTEST
  tests:
    name: pytest ${{ matrix.os }}::py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
        include:
          # we'll test the python support on ubuntu
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: 3.9
          - os: ubuntu-latest
            python-version: 3.7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up libjpegturbo Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libturbojpeg
      - name: Set up libjpegturbo OSX
        if: matrix.os == 'macos-latest'
        run: brew install jpeg-turbo
      - name: Set up libjpegturbo Windows
        shell: pwsh
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri https://sourceforge.net/projects/libjpeg-turbo/files/2.1.2/libjpeg-turbo-2.1.2-vc64.exe/download -OutFile libjpeg-turbo-2.1.2-vc64.exe -UserAgent "NativeHost"
          7z e libjpeg-turbo-2.1.2-vc64.exe -oC:\Windows\System32 bin/turbojpeg.dll

      - name: Update pip and install pytest
        run: |
          python -m pip install -U pip
          python -m pip install pytest

      - name: Install opentile
        run: python -m pip install .

      - name: Run tests
        run: pytest -v tests/
